# -----------------------------------------------------------------------------
# Name:         arc.py
# Purpose:      Object for storing the syntactic unit of an arc
#
# Author:       Robert Snarrenberg
# Copyright:    (c) 2022 by Robert Snarrenberg
# License:      BSD, see license.txt
# -----------------------------------------------------------------------------
"""
Arc
====

The Arc class stores information about an arc's syntactic function."""

# -----------------------------------------------------------------------------
# MAIN CLASS
# -----------------------------------------------------------------------------


class Arc():
    """An arc is a syntactic unit that comprises at least two notes.
    The main content of an arc is a list of note indexes.  Arcs are
    generated by the syntax parser.
    Types include passing, neighboring, repetition, and arpeggiation."""

    def __init__(self, arc=None):
        self.arc = arc  # list of note indexes
        self.content = None  # list of CSDs
        self.category = None  # basic, secondary
        self.type = None  # passing, neighboring, repetition, arpeggiation
        self.subtype  = None  # rising/falling, upper/lower
        self.notation_type = None  # slur, tie
        self.notation_style = None  # solid, dotted
        self.level = None  # integer, level of embedding

    def __repr__(self):
        return str(self.arc)



if __name__ == "__main__":
    # self_test code
    pass
# -----------------------------------------------------------------------------
# eof
